//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class IcsFiles {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal IcsFiles() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IcsFiles", typeof(IcsFiles).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] ALARM1 {
        get {
            object obj = ResourceManager.GetObject("ALARM1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] ALARM2 {
        get {
            object obj = ResourceManager.GetObject("ALARM2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] ALARM3 {
        get {
            object obj = ResourceManager.GetObject("ALARM3", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] ALARM4 {
        get {
            object obj = ResourceManager.GetObject("ALARM4", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] ALARM5 {
        get {
            object obj = ResourceManager.GetObject("ALARM5", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] ALARM6 {
        get {
            object obj = ResourceManager.GetObject("ALARM6", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] ALARM7 {
        get {
            object obj = ResourceManager.GetObject("ALARM7", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Attachment3 {
        get {
            object obj = ResourceManager.GetObject("Attachment3", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Attachment4 {
        get {
            object obj = ResourceManager.GetObject("Attachment4", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Attendee1 {
        get {
            object obj = ResourceManager.GetObject("Attendee1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Attendee2 {
        get {
            object obj = ResourceManager.GetObject("Attendee2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Bug1741093 {
        get {
            object obj = ResourceManager.GetObject("Bug1741093", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Bug2033495 {
        get {
            object obj = ResourceManager.GetObject("Bug2033495", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Bug2148092 {
        get {
            object obj = ResourceManager.GetObject("Bug2148092", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Bug2912657 {
        get {
            object obj = ResourceManager.GetObject("Bug2912657", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Bug2916581 {
        get {
            object obj = ResourceManager.GetObject("Bug2916581", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Bug2938007 {
        get {
            object obj = ResourceManager.GetObject("Bug2938007", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Bug2959692 {
        get {
            object obj = ResourceManager.GetObject("Bug2959692", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Bug2966236 {
        get {
            object obj = ResourceManager.GetObject("Bug2966236", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Bug3007244 {
        get {
            object obj = ResourceManager.GetObject("Bug3007244", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] ByMonth1 {
        get {
            object obj = ResourceManager.GetObject("ByMonth1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] ByMonth2 {
        get {
            object obj = ResourceManager.GetObject("ByMonth2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] ByMonthDay1 {
        get {
            object obj = ResourceManager.GetObject("ByMonthDay1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Calendar1 {
        get {
            object obj = ResourceManager.GetObject("Calendar1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] CalendarParameters2 {
        get {
            object obj = ResourceManager.GetObject("CalendarParameters2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] CaseInsensitive1 {
        get {
            object obj = ResourceManager.GetObject("CaseInsensitive1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] CaseInsensitive2 {
        get {
            object obj = ResourceManager.GetObject("CaseInsensitive2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] CaseInsensitive3 {
        get {
            object obj = ResourceManager.GetObject("CaseInsensitive3", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] CaseInsensitive4 {
        get {
            object obj = ResourceManager.GetObject("CaseInsensitive4", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Categories1 {
        get {
            object obj = ResourceManager.GetObject("Categories1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Daily1 {
        get {
            object obj = ResourceManager.GetObject("Daily1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] DailyByDay1 {
        get {
            object obj = ResourceManager.GetObject("DailyByDay1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] DailyByHourMinute1 {
        get {
            object obj = ResourceManager.GetObject("DailyByHourMinute1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] DailyCount1 {
        get {
            object obj = ResourceManager.GetObject("DailyCount1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] DailyCount2 {
        get {
            object obj = ResourceManager.GetObject("DailyCount2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] DailyInterval1 {
        get {
            object obj = ResourceManager.GetObject("DailyInterval1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] DailyInterval2 {
        get {
            object obj = ResourceManager.GetObject("DailyInterval2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] DailyUntil1 {
        get {
            object obj = ResourceManager.GetObject("DailyUntil1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] DateTime1 {
        get {
            object obj = ResourceManager.GetObject("DateTime1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] DateTime2 {
        get {
            object obj = ResourceManager.GetObject("DateTime2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Duration1 {
        get {
            object obj = ResourceManager.GetObject("Duration1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Empty1 {
        get {
            object obj = ResourceManager.GetObject("Empty1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] EmptyLines1 {
        get {
            object obj = ResourceManager.GetObject("EmptyLines1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] EmptyLines2 {
        get {
            object obj = ResourceManager.GetObject("EmptyLines2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] EmptyLines3 {
        get {
            object obj = ResourceManager.GetObject("EmptyLines3", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] EmptyLines4 {
        get {
            object obj = ResourceManager.GetObject("EmptyLines4", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Encoding1 {
        get {
            object obj = ResourceManager.GetObject("Encoding1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Encoding2 {
        get {
            object obj = ResourceManager.GetObject("Encoding2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Encoding3 {
        get {
            object obj = ResourceManager.GetObject("Encoding3", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Event1 {
        get {
            object obj = ResourceManager.GetObject("Event1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Event2 {
        get {
            object obj = ResourceManager.GetObject("Event2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Event3 {
        get {
            object obj = ResourceManager.GetObject("Event3", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Event4 {
        get {
            object obj = ResourceManager.GetObject("Event4", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] GeographicLocation1 {
        get {
            object obj = ResourceManager.GetObject("GeographicLocation1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Google1 {
        get {
            object obj = ResourceManager.GetObject("Google1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Hourly1 {
        get {
            object obj = ResourceManager.GetObject("Hourly1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] HourlyInterval1 {
        get {
            object obj = ResourceManager.GetObject("HourlyInterval1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] HourlyInterval2 {
        get {
            object obj = ResourceManager.GetObject("HourlyInterval2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] HourlyUntil1 {
        get {
            object obj = ResourceManager.GetObject("HourlyUntil1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] JOURNAL1 {
        get {
            object obj = ResourceManager.GetObject("JOURNAL1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] JOURNAL2 {
        get {
            object obj = ResourceManager.GetObject("JOURNAL2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Language1 {
        get {
            object obj = ResourceManager.GetObject("Language1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Language2 {
        get {
            object obj = ResourceManager.GetObject("Language2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Language3 {
        get {
            object obj = ResourceManager.GetObject("Language3", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Language4 {
        get {
            object obj = ResourceManager.GetObject("Language4", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Minutely1 {
        get {
            object obj = ResourceManager.GetObject("Minutely1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] MinutelyByHour1 {
        get {
            object obj = ResourceManager.GetObject("MinutelyByHour1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] MinutelyCount1 {
        get {
            object obj = ResourceManager.GetObject("MinutelyCount1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] MinutelyCount2 {
        get {
            object obj = ResourceManager.GetObject("MinutelyCount2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] MinutelyCount3 {
        get {
            object obj = ResourceManager.GetObject("MinutelyCount3", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] MinutelyCount4 {
        get {
            object obj = ResourceManager.GetObject("MinutelyCount4", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] MinutelyInterval1 {
        get {
            object obj = ResourceManager.GetObject("MinutelyInterval1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Monthly1 {
        get {
            object obj = ResourceManager.GetObject("Monthly1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] MonthlyByDay1 {
        get {
            object obj = ResourceManager.GetObject("MonthlyByDay1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] MonthlyByMonthDay1 {
        get {
            object obj = ResourceManager.GetObject("MonthlyByMonthDay1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] MonthlyByMonthDay2 {
        get {
            object obj = ResourceManager.GetObject("MonthlyByMonthDay2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] MonthlyBySetPos1 {
        get {
            object obj = ResourceManager.GetObject("MonthlyBySetPos1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] MonthlyBySetPos2 {
        get {
            object obj = ResourceManager.GetObject("MonthlyBySetPos2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] MonthlyCountByDay1 {
        get {
            object obj = ResourceManager.GetObject("MonthlyCountByDay1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] MonthlyCountByDay2 {
        get {
            object obj = ResourceManager.GetObject("MonthlyCountByDay2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] MonthlyCountByDay3 {
        get {
            object obj = ResourceManager.GetObject("MonthlyCountByDay3", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] MonthlyCountByMonthDay1 {
        get {
            object obj = ResourceManager.GetObject("MonthlyCountByMonthDay1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] MonthlyCountByMonthDay2 {
        get {
            object obj = ResourceManager.GetObject("MonthlyCountByMonthDay2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] MonthlyCountByMonthDay3 {
        get {
            object obj = ResourceManager.GetObject("MonthlyCountByMonthDay3", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] MonthlyInterval1 {
        get {
            object obj = ResourceManager.GetObject("MonthlyInterval1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] MonthlyUntilByDay1 {
        get {
            object obj = ResourceManager.GetObject("MonthlyUntilByDay1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Outlook2007LineFolds {
        get {
            object obj = ResourceManager.GetObject("Outlook2007LineFolds", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Parameter1 {
        get {
            object obj = ResourceManager.GetObject("Parameter1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Parameter2 {
        get {
            object obj = ResourceManager.GetObject("Parameter2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Parse1 {
        get {
            object obj = ResourceManager.GetObject("Parse1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] PARSE17 {
        get {
            object obj = ResourceManager.GetObject("PARSE17", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] ProdID1 {
        get {
            object obj = ResourceManager.GetObject("ProdID1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] ProdID2 {
        get {
            object obj = ResourceManager.GetObject("ProdID2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Property1 {
        get {
            object obj = ResourceManager.GetObject("Property1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] RecurrenceDates1 {
        get {
            object obj = ResourceManager.GetObject("RecurrenceDates1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] RequestStatus1 {
        get {
            object obj = ResourceManager.GetObject("RequestStatus1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Secondly1 {
        get {
            object obj = ResourceManager.GetObject("Secondly1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] TimeZone1 {
        get {
            object obj = ResourceManager.GetObject("TimeZone1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] TimeZone2 {
        get {
            object obj = ResourceManager.GetObject("TimeZone2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] TimeZone3 {
        get {
            object obj = ResourceManager.GetObject("TimeZone3", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Todo1 {
        get {
            object obj = ResourceManager.GetObject("Todo1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Todo2 {
        get {
            object obj = ResourceManager.GetObject("Todo2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Todo3 {
        get {
            object obj = ResourceManager.GetObject("Todo3", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Todo4 {
        get {
            object obj = ResourceManager.GetObject("Todo4", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Todo5 {
        get {
            object obj = ResourceManager.GetObject("Todo5", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Todo6 {
        get {
            object obj = ResourceManager.GetObject("Todo6", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Todo7 {
        get {
            object obj = ResourceManager.GetObject("Todo7", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Todo8 {
        get {
            object obj = ResourceManager.GetObject("Todo8", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Todo9 {
        get {
            object obj = ResourceManager.GetObject("Todo9", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Transparency1 {
        get {
            object obj = ResourceManager.GetObject("Transparency1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Transparency2 {
        get {
            object obj = ResourceManager.GetObject("Transparency2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Trigger1 {
        get {
            object obj = ResourceManager.GetObject("Trigger1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] USHolidays {
        get {
            object obj = ResourceManager.GetObject("USHolidays", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] WeeklyCount1 {
        get {
            object obj = ResourceManager.GetObject("WeeklyCount1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] WeeklyCountWkst1 {
        get {
            object obj = ResourceManager.GetObject("WeeklyCountWkst1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] WeeklyCountWkst2 {
        get {
            object obj = ResourceManager.GetObject("WeeklyCountWkst2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] WeeklyCountWkst3 {
        get {
            object obj = ResourceManager.GetObject("WeeklyCountWkst3", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] WeeklyCountWkst4 {
        get {
            object obj = ResourceManager.GetObject("WeeklyCountWkst4", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] WeeklyInterval1 {
        get {
            object obj = ResourceManager.GetObject("WeeklyInterval1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] WeeklyUntil1 {
        get {
            object obj = ResourceManager.GetObject("WeeklyUntil1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] WeeklyUntilWkst1 {
        get {
            object obj = ResourceManager.GetObject("WeeklyUntilWkst1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] WeeklyUntilWkst2 {
        get {
            object obj = ResourceManager.GetObject("WeeklyUntilWkst2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] WeeklyWeekStartsLastYear {
        get {
            object obj = ResourceManager.GetObject("WeeklyWeekStartsLastYear", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] WeeklyWkst1 {
        get {
            object obj = ResourceManager.GetObject("WeeklyWkst1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] XProperty1 {
        get {
            object obj = ResourceManager.GetObject("XProperty1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] XProperty2 {
        get {
            object obj = ResourceManager.GetObject("XProperty2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] Yearly1 {
        get {
            object obj = ResourceManager.GetObject("Yearly1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] YearlyByDay1 {
        get {
            object obj = ResourceManager.GetObject("YearlyByDay1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] YearlyByMonth1 {
        get {
            object obj = ResourceManager.GetObject("YearlyByMonth1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] YearlyByMonth2 {
        get {
            object obj = ResourceManager.GetObject("YearlyByMonth2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] YearlyByMonth3 {
        get {
            object obj = ResourceManager.GetObject("YearlyByMonth3", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] YearlyByMonthDay1 {
        get {
            object obj = ResourceManager.GetObject("YearlyByMonthDay1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] YearlyBySetPos1 {
        get {
            object obj = ResourceManager.GetObject("YearlyBySetPos1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] YearlyByWeekNo1 {
        get {
            object obj = ResourceManager.GetObject("YearlyByWeekNo1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] YearlyByWeekNo2 {
        get {
            object obj = ResourceManager.GetObject("YearlyByWeekNo2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] YearlyByWeekNo3 {
        get {
            object obj = ResourceManager.GetObject("YearlyByWeekNo3", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] YearlyByWeekNo4 {
        get {
            object obj = ResourceManager.GetObject("YearlyByWeekNo4", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] YearlyByWeekNo5 {
        get {
            object obj = ResourceManager.GetObject("YearlyByWeekNo5", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] YearlyComplex1 {
        get {
            object obj = ResourceManager.GetObject("YearlyComplex1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] YearlyCountByMonth1 {
        get {
            object obj = ResourceManager.GetObject("YearlyCountByMonth1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] YearlyCountByYearDay1 {
        get {
            object obj = ResourceManager.GetObject("YearlyCountByYearDay1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    internal static byte[] YearlyInterval1 {
        get {
            object obj = ResourceManager.GetObject("YearlyInterval1", resourceCulture);
            return ((byte[])(obj));
        }
    }
}
